# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_als_nnmf_dense <- function(V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_total_loss, log_ortho_loss, log_test_loss, log_sparsity, num_threads) {
    .Call(`_nnmf_cpp_als_nnmf_dense`, V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_total_loss, log_ortho_loss, log_test_loss, log_sparsity, num_threads)
}

cpp_als_nnmf_sparse <- function(V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_total_loss, log_ortho_loss, log_test_loss, log_sparsity, num_threads) {
    .Call(`_nnmf_cpp_als_nnmf_sparse`, V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_total_loss, log_ortho_loss, log_test_loss, log_sparsity, num_threads)
}

