# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_als_nmf_dense_densemask <- function(V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_ortho_loss, log_train_loss, log_test_loss, log_sparsity, num_threads, mask, mask_zeros) {
    .Call(`_RcppML_cpp_als_nmf_dense_densemask`, V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_ortho_loss, log_train_loss, log_test_loss, log_sparsity, num_threads, mask, mask_zeros)
}

cpp_als_nmf_dense_sparsemask <- function(V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_ortho_loss, log_train_loss, log_test_loss, log_sparsity, num_threads, mask, mask_zeros) {
    .Call(`_RcppML_cpp_als_nmf_dense_sparsemask`, V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_ortho_loss, log_train_loss, log_test_loss, log_sparsity, num_threads, mask, mask_zeros)
}

cpp_als_nmf_sparse_sparsemask <- function(V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_ortho_loss, log_train_loss, log_test_loss, log_sparsity, num_threads, mask, mask_zeros) {
    .Call(`_RcppML_cpp_als_nmf_sparse_sparsemask`, V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_ortho_loss, log_train_loss, log_test_loss, log_sparsity, num_threads, mask, mask_zeros)
}

cpp_als_nmf_sparse_densemask <- function(V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_ortho_loss, log_train_loss, log_test_loss, log_sparsity, num_threads, mask, mask_zeros) {
    .Call(`_RcppML_cpp_als_nmf_sparse_densemask`, V, k, inv_test_size, test_seed, W, tol, epochs, verbose, L1, L2, ortho, log_ortho_loss, log_train_loss, log_test_loss, log_sparsity, num_threads, mask, mask_zeros)
}

