# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_als_nnmf <- function(A, k, inv_test_size, test_seed, w, tol, epochs, verbose, L1, L2, ortho, log_train_loss, log_test_loss, num_threads) {
    .Call(`_nnmf_cpp_als_nnmf`, A, k, inv_test_size, test_seed, w, tol, epochs, verbose, L1, L2, ortho, log_train_loss, log_test_loss, num_threads)
}

